FIX   Model/iBeaconTransmitService.cs(12,43): error CS0246: The type or namespace name 'IIBeaconTransmitService' could not be found (are you missing a using directive or an assembly reference?) [/Users/runner/runners/2.165.2/work/1/s/Covid19Radar/Covid19Radar.iOS/Covid19Radar.iOS.csproj]   Model/iBeaconTransmitService.cs(38,39): error CS0246: The type or namespace name 'iBeacon' could not be found (are you missing a using directive or an assembly reference?) [/Users/runner/runners/2.165.2/work/1/s/Covid19Radar/Covid19Radar.iOS/Covid19Radar.iOS.csproj]